SELECT
  CONCAT(CONCAT('"', NVL(A1.NAME_C, NVL(A1.DISPLAYNAME_C, NVL(A1.LABEL_C, '')))), '"') AS "APP_NAME",
  -- TODO use CASE here
	REPLACE(REPLACE(A1.JDOCLASS_C, 'com.collation.topomgr.jdo.topology.', ''), 'Jdo', '') AS "TYPE",
	CONCAT(CONCAT('"', A1.VENDORNAME_C), '"') AS VENDOR_NAME,
	CONCAT(CONCAT('"', A1.PRODUCTNAME_C), '"') AS PRODUCT_NAME,
	CONCAT(CONCAT('"', A1.PRODUCTVERSION_C), '"') AS PRODUCT_VERSION,
	CONCAT(CONCAT('"', CS1.DISPLAYNAME_C), '"') AS FQDN
FROM 
	BB_APPSERVER6_V A1
	
LEFT OUTER JOIN ( 
	SELECT
		PK_C,
		DISPLAYNAME_C
	FROM 
		BB_COMPUTERSYSTEM40_V
) CS1 ON A1.PK__HOST_C = CS1.PK_C