-- errors while executing collectionengine during last week (excluding file copy errors)
SELECT DISTINCT
 dai1.DE_IP IP
,d1.EVENT_ATTRIBUTE SENSOR
,d1.EVENT_DESC
FROM
 DISCEVNT d1, DISCEVNT_ATTR_IP dai1, DISCEVNT_RUN dr1
WHERE
 (d1.EVENT_ATTRIBUTE = dai1.DE_ATTR ) AND
 (d1.EVENT_RUNID = dr1.DE_RUN_ID) AND
 d1.EVENT_DESC LIKE '%CTJTD1606E%' AND
 dr1.DE_START_WEEK_DATE IN
  ( SELECT * FROM ( SELECT DISTINCT DE_START_WEEK_DATE FROM DISCEVNT_RUN ORDER BY DE_START_WEEK_DATE DESC )
  -- DB2
  FETCH FIRST 1 ROWS ONLY )
  AND NOT EXISTS
  (
     SELECT 1
     FROM DISCEVNT d2, DISCEVNT_ATTR_IP dai2, DISCEVNT_RUN dr2
     WHERE
     d2.EVENT_ATTRIBUTE = dai2.DE_ATTR
     AND d2.EVENT_RUNID = dr2.DE_RUN_ID
     AND d2.EVENT_DESC like 'CTJTD1606W%'
     AND d1.EVENT_ATTRIBUTE = d2.EVENT_ATTRIBUTE
     AND dai1.DE_IP = dai2.DE_IP
     AND dr2.DE_START_WEEK_DATE IN
          ( SELECT * FROM ( SELECT DISTINCT DE_START_WEEK_DATE FROM DISCEVNT_RUN ORDER BY DE_START_WEEK_DATE DESC )
            -- DB2
            FETCH FIRST 1 ROWS ONLY )
            -- Oracle
            --WHERE ROWNUM <= 2 )
  )
