SELECT
 VOL.NAME_C AS "Volume",
 CASE WHEN CS.NAME_C = 'vfiler0' THEN CS.FQDN_C
  ELSE CS.NAME_C
 END AS "SVM",
 T3.DISPLAYNAME_C AS "Cluster"
 --, CS.GUID_C AS GUID
FROM BB_STORAGEVOLUME95_V VOL
JOIN BB_STORAGESUBSYSTEM16_V CS ON VOL.PK__PARENTSTORAGEEXTENT_C = CS.PK_C
LEFT OUTER JOIN BB_COMPUTERSYSTSTER_CFD2DE75J T2 ON CS.PK_C = T2.PK__JDOID_C
LEFT OUTER JOIN BB_COMPUTERSYSTEMCLUSTER66_V T3 ON T3.PK_C = T2.PK__SYSTEMSCLUSTER_C
WHERE
VOL.TYPE_C = 'flexible'
ORDER BY lower(T3.DISPLAYNAME_C), lower(CS.NAME_C), lower(VOL.NAME_C)
