WITH
ARRAYS AS (
 SELECT 
  CS_PK,
  LISTAGG(ARRAY_NAME, ';') AS ARRAY_NAMES
 FROM 
 (
	 SELECT
	  DISTINCT
	  CS.PK_C AS CS_PK,
	  ARRAY.DISPLAYNAME_C AS ARRAY_NAME
	 FROM
	  BB_UNITARYCOMPUTERSYSTEM24_V CS,
	  BB_SCSIVOLUME2_V SE,
	  BB_STORAGEEXTENTJDO_BASEDON_J SE_BOVPLEX,
	  BB_BASEDONEXTENT34_V BOVPLEX,
	  BB_STORAGEVOLUME95_V VVOL,
	  BB_STORAGEEXTENTJDO_BASEDON_J VVOL_BOARRAY,
	  BB_BASEDONEXTENT34_V BOARRAY,
	  BB_STORAGEVOLUME95_V LUN,
	  BB_STORAGESUBSYSTEM16_V ARRAY
	 WHERE
	  SE.PK__PARENTSTORAGEEXTENT_C = CS.PK_C 
	  AND SE.PK_C = SE_BOVPLEX.PK__JDOID_C
	  AND BOVPLEX.PK_C = SE_BOVPLEX.PK__BASEDON_C
	  AND BOVPLEX.TARGET_C = VVOL.GUID_C
	  AND VVOL.PK_C = VVOL_BOARRAY.PK__JDOID_C
	  AND BOARRAY.PK_C = VVOL_BOARRAY.PK__BASEDON_C
	  AND BOARRAY.TARGET_C = LUN.GUID_C
	  AND LUN.PK__PARENTSTORAGEEXTENT_C = ARRAY.PK_C
	  AND ARRAY.MODEL_C NOT LIKE '%VPLEX%'
 )
 GROUP BY CS_PK
)
SELECT
 ARRAYS.ARRAY_NAMES AS ARRAY_NAMES,
 lower(CS.DISPLAYNAME_C) AS CS_NAME,
-- CS.LASTMODIFIEDTIME_T AS CS_LMT,
 OS.OSNAME_C AS OSNAME
FROM
 BB_UNITARYCOMPUTERSYSTEM24_V CS
 LEFT OUTER JOIN BB_OPERATINGSYSTEM62_V OS ON CS.PK__OSRUNNING_C = OS.PK_C,
 ARRAYS
WHERE 
 (CS.VIRTUAL_C IS NULL OR CS.VIRTUAL_C = 0)
 AND CS.JDOCLASS_C NOT LIKE '%Vmware%'
 AND CS.JDOCLASS_C NOT LIKE '%.UnitaryComputer%'
 AND ARRAYS.CS_PK = CS.PK_C
 AND CS.PK_C NOT IN ( SELECT PK__HOST_C FROM BB_HYPERV12_V WHERE PK__HOST_C IS NOT NULL )
 --AND (current timestamp - 14 days) < (timestamp('1970-01-01','00.00.00') + (CS.LASTMODIFIEDTIME_C/1000) seconds )