SELECT DISTINCT
 dai1.DE_IP IP
,d1.EVENT_ATTRIBUTE SENSOR
FROM 
 DISCEVNT d1, DISCEVNT_ATTR_IP dai1, DISCEVNT_RUN dr1 
WHERE 
 (d1.EVENT_ATTRIBUTE = dai1.DE_ATTR ) AND 
 (d1.EVENT_RUNID = dr1.DE_RUN_ID) AND 
 d1.EVENT_SEVERITY = 5 AND 
 dai1.DE_SENSOR = 'SessionSensor' AND 
 dr1.DE_START_WEEK_DATE IN 
  ( SELECT * FROM ( SELECT DISTINCT DE_START_WEEK_DATE FROM DISCEVNT_RUN ORDER BY DE_START_WEEK_DATE DESC )
  -- DB2
  FETCH FIRST 2 ROWS ONLY )
  -- Oracle
  --WHERE ROWNUM <= 2 )
  AND NOT EXISTS
  (
     SELECT 1
     FROM DISCEVNT d2, DISCEVNT_ATTR_IP dai2, DISCEVNT_RUN dr2
     WHERE
     d2.EVENT_ATTRIBUTE = dai2.DE_ATTR
     AND d2.EVENT_RUNID = dr2.DE_RUN_ID
     AND ( dai2.DE_SENSOR = 'SessionSensor' OR dai2.DE_SENSOR = 'SnmpMib2Sensor' )
     AND d2.EVENT_DESC like 'Discovered:%'
     AND d1.EVENT_ATTRIBUTE = d2.EVENT_ATTRIBUTE
     AND dai1.DE_IP = dai2.DE_IP
     AND dr2.DE_START_WEEK_DATE IN 
          ( SELECT * FROM ( SELECT DISTINCT DE_START_WEEK_DATE FROM DISCEVNT_RUN ORDER BY DE_START_WEEK_DATE DESC )
	    -- DB2
            FETCH FIRST 2 ROWS ONLY )
            -- Oracle
            --WHERE ROWNUM <= 2 )
  )

