SELECT DISTINCT
devnt.EVENT_ATTRIBUTE ATTR, devnt.EVENT_SEVERITY,
CASE 
devnt.EVENT_SEVERITY
WHEN 4 THEN 'Warning'
WHEN 5 THEN 'Error'
END SEV,
devnt.EVENT_DESC DESCRIP,
dai1.DE_IP IP,
dai1.DE_HOSTNAME HOST,
dai1.DE_FQDN FQDN,
dai1.DE_SENSOR SENSOR,
DISCEVNT_RUN.DE_START_WEEK_DATE,
DISCEVNT_RUN.DE_RUN_ID,
dai1.DE_SERVER,
devnt.EVENT_RUNID DISC_RUNID,
devnt.EVENT_TIME,
DISCRUN.SERVERID_X SERVERID
from DISCEVNT devnt, DISCEVNT_ATTR_IP dai1, DISCEVNT_RUN, DISCRUN
where
devnt.EVENT_ATTRIBUTE = dai1.DE_ATTR
and devnt.EVENT_RUNID = DISCEVNT_RUN.DE_RUN_ID 
and devnt.EVENT_SEVERITY in (5 , 4) 
and dai1.DE_SENSOR = 'SessionSensor'
and DISCEVNT_RUN.DE_START_WEEK_DATE = ?
and DISCRUN.DISCOVERRUNID_X = DISCEVNT_RUN.DE_RUN_ID
and devnt.EVENT_DESC LIKE '%CTJTP1160E%'
and not exists
(
	SELECT 1
	from DISCEVNT devnt2, DISCEVNT_ATTR_IP dai2, DISCEVNT_RUN
	where
	(devnt2.EVENT_ATTRIBUTE = dai2.DE_ATTR ) 
	and (devnt2.EVENT_RUNID = DISCEVNT_RUN.DE_RUN_ID) 
	and (
	    (devnt2.EVENT_ATTRIBUTE like '%SnmpMib2%' or devnt2.EVENT_ATTRIBUTE like '%ComputerSystem%' or devnt2.EVENT_ATTRIBUTE like '%Generic%' or devnt2.EVENT_ATTRIBUTE like '%SessionSensor%')
	    and devnt2.EVENT_ATTRIBUTE not like '%Custom%' )
	and DISCEVNT_RUN.DE_START_WEEK_DATE = ?
	and devnt2.EVENT_DESC like 'Discovered:%'
	and devnt.EVENT_ATTRIBUTE = devnt2.EVENT_ATTRIBUTE
	and devnt.EVENT_ATTRIBUTE = devnt2.EVENT_ATTRIBUTE
	and dai1.DE_IP = dai2.DE_IP
)
order by DESCRIP , HOST