-- query all Solaris with an FCVolume
SELECT
DISTINCT CS.DISPLAYNAME_C
FROM
BB_SUNSPARCUNITARYCOMPUTE1_V CS
INNER JOIN BB_FCVOLUME55_V FCV ON FCV.PK__PARENTSTORAGEEXTENT_C = CS.PK_C
WHERE CS.PK_C NOT IN (
	-- all Solaris with storage connected to VPLEX
	SELECT DISTINCT CS.PK_C FROM
	BB_SUNSPARCUNITARYCOMPUTE1_V CS
	LEFT JOIN BB_STORAGEVOLUME95_V SV ON SV.PK__PARENTSTORAGEEXTENT_C = CS.PK_C
	LEFT JOIN BB_STORAGEEXTENTJDO_BASEDON_J SV_BOE ON SV.PK_C = SV_BOE.PK__JDOID_C
	LEFT JOIN BB_BASEDONEXTENT34_V BOE ON BOE.PK_C = SV_BOE.PK__BASEDON_C
	LEFT JOIN BB_STORAGEVOLUME95_V VPLEXSV ON BOE.TARGET_C = VPLEXSV.GUID_C
	LEFT JOIN BB_STORAGESUBSYSTEM16_V VPLEX ON VPLEXSV.PK__PARENTSTORAGEEXTENT_C = VPLEX.PK_C
	WHERE
	VPLEX.MODEL_C LIKE '%VPLEX%'
)