WITH RDM AS (
SELECT
VM.PK_C AS VM_PK,
SUM(SE.NUMOFBLOCKS_C) AS NUMOFBLOCKS
FROM
BB_COMPUTERSYSTEM40_V VM,
BB_COMPUTERSYSTTENT_81F02D6EJ VM_SE,
BB_STORAGEEXTENT15_V SE
WHERE 
VM.PK_C = VM_SE.PK__JDOID_C
AND SE.PK_C = VM_SE.PK__STORAGEEXTENT_C
AND (SE.MANAGEDSYSTEMNAME_C IS NOT NULL
OR CAST(SE.DESCRIPTION_C AS VARCHAR(50)) = 'RDM')
GROUP BY VM.PK_C
),
DATASTORES AS (
SELECT
VM.PK_C AS VM_PK,
CAST(NVL(SUM(DS.CAPACITY_C), 0) / 1024 AS FLOAT) AS DS_CAPACITY_GB,
CAST((NVL(SUM(DS.CAPACITY_C), 0) - NVL(SUM(DS.FREESPACE_C), 0)) / 1024 AS FLOAT) AS DS_CONSUMED_GB
FROM
BB_COMPUTERSYSTEM40_V VM
LEFT OUTER JOIN BB_COMPUTERSYSTTORE_EC31D1D0J VM_DS ON VM.PK_C = VM_DS.PK__JDOID_C
LEFT OUTER JOIN BB_VMWAREDATASTORE9_V DS ON DS.PK_C = VM_DS.PK__RESIDESONVMWAREDATASTORE_C
GROUP BY VM.PK_C
),
PHYS_HOSTS AS (
SELECT
VM.PK_C AS VM_PK,
LISTAGG(ESX.DISPLAYNAME_C, ';') AS ESX
FROM
BB_VMWAREUNITARYCOMPUTERS70_V ESX,
BB_COMPUTERSYSTEM40_V VM
WHERE 
VM.PK__HOSTSYSTEM_C = ESX.PK_C
GROUP BY VM.PK_C
)
SELECT
lower(PHYS_HOSTS.ESX) AS Physical_Server_Name,
lower(VM.NAME_C) AS VM_Name,
lower(NVL(VM.FQDN_C, '')) AS HostName,
VM.UUID_C AS UUID,
VM.LASTMODIFIEDTIME_T AS VM_LMT,
CLUS.DISPLAYNAME_C AS Host_Cluster_Name,
CAST(ROUND(NVL(RDM.NUMOFBLOCKS, 0) * 0.00000047683715820313, 2) AS FLOAT) AS RDM_CAPACITY_GB,
DATASTORES.DS_CAPACITY_GB AS DS_CAPACITY_GB,
DATASTORES.DS_CONSUMED_GB AS DS_CONSUMED_GB
FROM
BB_DATACENTER83_V DC,
BB_DATACENTERJDO_CLUSTERS_J DC_CLUS,
BB_VMWARECLUSTER10_V CLUS,
BB_COMPUTERSYSTTEMS_A267EEF0J CLUS_ESX,
BB_VMWAREUNITARYCOMPUTERS70_V ESX,
BB_COMPUTERSYSTSTEM_238A0E48J ESX_VM,
BB_COMPUTERSYSTEM40_V VM
LEFT OUTER JOIN RDM ON RDM.VM_PK = VM.PK_C
LEFT OUTER JOIN DATASTORES ON DATASTORES.VM_PK = VM.PK_C,
PHYS_HOSTS
WHERE PHYS_HOSTS.VM_PK = VM.PK_C
AND DC.PK_C = DC_CLUS.PK__JDOID_C
AND CLUS.PK_C = DC_CLUS.PK__CLUSTERS_C
AND CLUS.PK_C = CLUS_ESX.PK__JDOID_C
AND ESX.PK_C = CLUS_ESX.PK__COMPUTERSYSTEMS_C
AND ESX.PK_C = ESX_VM.PK__JDOID_C
AND VM.PK_C = ESX_VM.PK__CHILDSYSTEM_C
AND (current timestamp - 14 days) < (timestamp('1970-01-01','00.00.00') + (VM.LASTMODIFIEDTIME_C/1000) seconds )
UNION
SELECT
lower(PHYS_HOSTS.ESX) AS Physical_Server_Name,
lower(VM.NAME_C) AS VM_Name,
lower(NVL(VM.FQDN_C, '')) AS HostName,
VM.UUID_C AS UUID,
VM.LASTMODIFIEDTIME_T AS VM_LMT,
CLUS.DISPLAYNAME_C AS Host_Cluster_Name,
CAST(ROUND(NVL(RDM.NUMOFBLOCKS, 0) * 0.00000047683715820313, 2) AS FLOAT) AS RDM_CAPACITY_GB,
DATASTORES.DS_CAPACITY_GB AS DS_CAPACITY_GB,
DATASTORES.DS_CONSUMED_GB AS DS_CONSUMED_GB
FROM
BB_DATACENTER83_V DC,
BB_DATACENTERJDO_SYSTEMS_J DC_ESX,
BB_VMWAREUNITARYCOMPUTERS70_V ESX,
BB_COMPUTERSYSTSTEM_238A0E48J ESX_VM,
BB_COMPUTERSYSTEM40_V VM
LEFT OUTER JOIN RDM ON RDM.VM_PK = VM.PK_C
LEFT OUTER JOIN DATASTORES ON DATASTORES.VM_PK = VM.PK_C,
PHYS_HOSTS,
BB_COMPUTERSYSTSTER_CFD2DE75J ESX_CLUS,
BB_COMPUTERSYSTEMCLUSTER66_V CLUS
WHERE PHYS_HOSTS.VM_PK = VM.PK_C
AND DC.PK_C = DC_ESX.PK__JDOID_C
AND ESX.PK_C = DC_ESX.PK__SYSTEMS_C
AND ESX.PK_C = ESX_VM.PK__JDOID_C
AND VM.PK_C = ESX_VM.PK__CHILDSYSTEM_C
AND ESX.PK_C = ESX_CLUS.PK__JDOID_C
AND CLUS.PK_C = ESX_CLUS.PK__SYSTEMSCLUSTER_C
AND (current timestamp - 14 days) < (timestamp('1970-01-01','00.00.00') + (VM.LASTMODIFIEDTIME_C/1000) seconds )
UNION
SELECT
lower(PHYS_HOSTS.ESX) AS Physical_Server_Name,
lower(VM.NAME_C) AS VM_Name,
lower(NVL(VM.FQDN_C, '')) AS HostName,
VM.UUID_C AS UUID,
VM.LASTMODIFIEDTIME_T AS VM_LMT,
CLUS.DISPLAYNAME_C AS Host_Cluster_Name,
CAST(ROUND(NVL(RDM.NUMOFBLOCKS, 0) * 0.00000047683715820313, 2) AS FLOAT) AS RDM_CAPACITY_GB,
DATASTORES.DS_CAPACITY_GB AS DS_CAPACITY_GB,
DATASTORES.DS_CONSUMED_GB AS DS_CONSUMED_GB
FROM
BB_DATACENTER83_V DC,
BB_DATACENTERJDO_SYSTEMS_J DC_ESX,
BB_VMWAREUNITARYCOMPUTERS70_V ESX,
BB_COMPUTERSYSTEM40_V VM
LEFT OUTER JOIN RDM ON RDM.VM_PK = VM.PK_C
LEFT OUTER JOIN DATASTORES ON DATASTORES.VM_PK = VM.PK_C,
PHYS_HOSTS,
BB_COMPUTERSYSTSTER_CFD2DE75J ESX_CLUS,
BB_COMPUTERSYSTEMCLUSTER66_V CLUS
WHERE PHYS_HOSTS.VM_PK = VM.PK_C
AND DC.PK_C = DC_ESX.PK__JDOID_C
AND ESX.PK_C = DC_ESX.PK__SYSTEMS_C
AND VM.PK__HOSTSYSTEM_C = ESX.PK_C
AND ESX.PK_C = ESX_CLUS.PK__JDOID_C
AND CLUS.PK_C = ESX_CLUS.PK__SYSTEMSCLUSTER_C
AND (current timestamp - 14 days) < (timestamp('1970-01-01','00.00.00') + (VM.LASTMODIFIEDTIME_C/1000) seconds )
UNION
SELECT
lower(PHYS_HOSTS.ESX) AS Physical_Server_Name,
lower(VM.NAME_C) AS VM_Name,
lower(NVL(VM.FQDN_C, '')) AS HostName,
VM.UUID_C AS UUID,
VM.LASTMODIFIEDTIME_T AS VM_LMT,
CLUS.DISPLAYNAME_C AS Host_Cluster_Name,
CAST(ROUND(NVL(RDM.NUMOFBLOCKS, 0) * 0.00000047683715820313, 2) AS FLOAT) AS RDM_CAPACITY_GB,
DATASTORES.DS_CAPACITY_GB AS DS_CAPACITY_GB,
DATASTORES.DS_CONSUMED_GB AS DS_CONSUMED_GB
FROM
BB_DATACENTER83_V DC,
BB_DATACENTERJDO_CLUSTERS_J DC_CLUS,
BB_VMWARECLUSTER10_V CLUS,
BB_COMPUTERSYSTTEMS_A267EEF0J CLUS_ESX,
BB_VMWAREUNITARYCOMPUTERS70_V ESX,
BB_COMPUTERSYSTEM40_V VM
LEFT OUTER JOIN RDM ON RDM.VM_PK = VM.PK_C
LEFT OUTER JOIN DATASTORES ON DATASTORES.VM_PK = VM.PK_C,
PHYS_HOSTS
WHERE PHYS_HOSTS.VM_PK = VM.PK_C
AND DC.PK_C = DC_CLUS.PK__JDOID_C
AND CLUS.PK_C = DC_CLUS.PK__CLUSTERS_C
AND CLUS.PK_C = CLUS_ESX.PK__JDOID_C
AND ESX.PK_C = CLUS_ESX.PK__COMPUTERSYSTEMS_C
AND ESX.PK_C = VM.PK__HOSTSYSTEM_C
AND (current timestamp - 14 days) < (timestamp('1970-01-01','00.00.00') + (VM.LASTMODIFIEDTIME_C/1000) seconds )